###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      working_dir: /app
      volumes:
        - .:/app
      environment:
        - MYSQL_ROOT_PASSWORD=dalro1707
        - MYSQL_DATABASE=local_metricontrol
        - MYSQL_USER=local_metricontrol
        - MYSQL_PASSWORD=dalro1707
      ports:
        - "3306:3306"
      expose:
        - "3306"

    php:
      build: php7yii
      working_dir: /app
      volumes:
        - .:/var/www
        - ./public_html:/var/www/public_html
        - ./php7yii/000-default.conf:/etc/apache2/sites-available/000-default.conf
        - ./php7yii/docker-php.conf:/etc/apache2/conf-available/docker-php.conf
        - ./php7yii/apache2.conf:/etc/apache2/apache2.conf
      ports:
       - "80:80"
      links:
       - mariadb
